export const CONTACTS_LOADED = "LOAD_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const USER_LOADED = "USER_LOADED";
export const ADD_PROFILE = "ADD_PROFILE";
export const LOADED_USER_AND_CONTACTS = "LOADED_USER_AND_CONTACTS";
